#include <nds.h>
#include <stdio.h>
#include <../lib/gl2d.h>

#include "../h/bitmapfont.h"

#include "../h/gamestate.h"
#include "../h/gameengine.h"
#include "../h/gamestate.h"

#include "../h/global.h"

Intro Intro::_state;

void Intro::Init()
{		
	bgSetPriority(0, 1);
	vramSetBankI( VRAM_I_SUB_BG_0x06208000 );	
	vramSetBankA( VRAM_A_TEXTURE );
	vramSetBankE(VRAM_E_TEX_PALETTE); 
	
	font_small.Load( FontImages,				// pointer to glImage array
			   FONT_8X8_NUM_IMAGES, 		// Texture packer auto-generated #define
			   font_8x8_texcoords,		// Texture packer auto-generated array
			   GL_RGB256,				// texture type for glTexImage2D() in videoGL.h 
			   TEXTURE_SIZE_64,			// sizeX for glTexImage2D() in videoGL.h
			   TEXTURE_SIZE_128,		// sizeY for glTexImage2D() in videoGL.h
			   GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT, // param for glTexImage2D() in videoGL.h
			   256,						// Length of the palette (256 colors)
			   (u16*)font_8x8Pal,		// Palette Data
			   (u8*)font_8x8Bitmap		// image data generated by GRIT 
			 );
			 
	consoleSelect(&bottomScreen);
    iprintf("Intro.ctor\n");
}

void Intro::Dispose()
{
	
}

void Intro::Pause()
{
	
}

void Intro::Resume()
{

}

void Intro::HandleEvents(GameEngine* game)
{
	scanKeys();
	int held = keysHeld();
	if(held & KEY_A) game->ChangeState(Menu::Instance());
}



void Intro::Update(GameEngine* game) 
{
	
}

void Intro::Render(GameEngine* game) 
{	
	glBegin2D();        
	
	glBoxFilledGradient( 0, 0, 0, 0,
								 RGB15( 31,  0,  0 ),
								 RGB15(  0, 31,  0 ),
								 RGB15( 31,  0, 31 ),
								 RGB15(  0, 31, 31 )
                               );
			
	glColor( RGB15(0,31,31) );
		
	font_small.PrintCentered( 0, 100, "FLAPPY NYAN" );
	font_small.PrintCentered( 0, 120, "Press any button to start" );
	
	glEnd2D();
	glFlush(0);                    		
	
	swiWaitForVBlank();
}
