#include <nds.h>
#include <stdio.h>
#include <../lib/gl2d.h>

#include "../h/bitmapfont.h"
#include "font.h"
#include "font_8x8.h"
#include "../h/font_8x8_uv.h"

#include "../h/gamestate.h"
#include "../h/gameengine.h"
#include "../h/gamestate.h"

Intro Intro::_state;

ConsoleFont font;
BitmapFont Font;

PrintConsole topScreen;
PrintConsole bottomScreen;
glImage  FontImages[FONT_8X8_NUM_IMAGES];

void Intro::Init()
{	
	consoleInit(&topScreen,1, BgType_Text4bpp, BgSize_T_256x256, 31,0, true, false);
	bgSetPriority(0, 1);

	vramSetBankI( VRAM_I_SUB_BG_0x06208000 );
	consoleInit( &bottomScreen, 0, BgType_Text4bpp, BgSize_T_256x256, 20, 0, false, false );	
	

	font.gfx = (u16*)fontTiles;
	font.pal = (u16*)fontPal;
	font.numChars = 95;
	font.numColors =  fontPalLen / 2;
	font.bpp = 4;
	font.asciiOffset = 32;
	font.convertSingleColor = false;			
	consoleSetFont(&bottomScreen, &font);

	vramSetBankA( VRAM_A_TEXTURE );
	vramSetBankE(VRAM_E_TEX_PALETTE); 
	
	Font.Load( FontImages,				// pointer to glImage array
			   FONT_8X8_NUM_IMAGES, 		// Texture packer auto-generated #define
			   font_8x8_texcoords,		// Texture packer auto-generated array
			   GL_RGB256,				// texture type for glTexImage2D() in videoGL.h 
			   TEXTURE_SIZE_64,			// sizeX for glTexImage2D() in videoGL.h
			   TEXTURE_SIZE_128,		// sizeY for glTexImage2D() in videoGL.h
			   GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT, // param for glTexImage2D() in videoGL.h
			   256,						// Length of the palette (256 colors)
			   (u16*)font_8x8Pal,		// Palette Data
			   (u8*)font_8x8Bitmap		// image data generated by GRIT 
			 );
}

void Intro::Dispose()
{
	
}

void Intro::Pause()
{
	
}

void Intro::Resume()
{

}

void Intro::HandleEvents(GameEngine* game)
{
	
}

void Intro::Update(GameEngine* game) 
{
	
}

void Intro::Render(GameEngine* game) 
{	
	glBegin2D();        
	// Do stuff
	glEnd2D();
	glFlush(0);                    	

	consoleSelect(&topScreen);	
    iprintf("FlappyNyan\n");   
    consoleSelect(&bottomScreen);
    iprintf("Press any button or tap screen\nto begin");
	
	swiWaitForVBlank();
}
